---
urls:
  - https://www.ldlc.com/es-es/ficha/PB00408672.html
  - https://www.ldlc.com/es-es/ficha/PB12481248.html
  - https://www.ldlc.com/es-es/ficha/PB00228886.html
  - https://www.ldlc.com/es-es/ficha/PB00228886.html
  - https://www.ldlc.com/es-es/ficha/PB00394343.html
...
